[platformio]
default_envs = m5stack

[env:m5stack]
platform = espressif32@6.10.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@0.4.6
    https://github.com/m5stack/M5-Max3421E-USBShield.git#29544f5c0e118c8bb5f895fccfa8ce9141e8ce1b
build_src_filter = +<main.cpp>

[env:screen-test]
platform = espressif32@6.10.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_deps = m5stack/M5Stack@0.4.6
build_src_filter = +<screen_test.cpp>
