[env:core-basic]
platform = espressif32@6.10.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@0.4.6
    https://github.com/felis/USB_Host_Shield_2.0.git#e5bc9950ba5389b67ad99175c312154af53df71d
    bblanchon/ArduinoJson@7.4.2
extra_scripts = post:scripts/usb_pins.py
