#pragma once
const char WEB_PAGE[] PROGMEM=R"HTML(<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Liquid handler · Teach</title>
<style>
:root{font:16px system-ui;color:#153332;background:#edf3ef}body{max-width:1060px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:28px;margin:4px 0}h2{font-size:19px;margin-top:0}small,.hint{color:#58716a;font-size:14px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:22px}section{background:white;border:1px solid #d8e4dd;border-radius:16px;padding:22px}button,select,input{font:inherit;border-radius:8px;border:1px solid #b6cbc0;padding:10px;background:white;color:#153332}button{cursor:pointer}button:hover{background:#e2efe8}button:disabled{opacity:.4;cursor:default}.primary{background:#176b53;color:white}.primary:hover{background:#115540}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}.status{background:#dceae1;border-radius:10px;padding:12px;margin:16px 0}.pos{font-size:23px;font-variant-numeric:tabular-nums;letter-spacing:1px}#error{color:#972f25;white-space:pre-wrap}.wide{grid-column:1/-1}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:9px 5px;border-bottom:1px solid #e3ebe5}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:5px;margin-top:18px}.well{font-size:11px;text-align:center;border:1px solid #d9e4dd;border-radius:50%;aspect-ratio:1;display:grid;place-items:center;background:#f6faf7}.well.anchor{background:#d0e9db;border-color:#3e9571}.well.check{background:#f4e5bd;border-color:#bc973f}pre{font-size:12px;background:#102e2a;color:#d7eee2;max-height:200px;overflow:auto;padding:14px;border-radius:10px;white-space:pre-wrap}label{display:block;margin:10px 0}.tag{font-size:12px;text-transform:uppercase;letter-spacing:1.5px;color:#38735a}a{color:#176b53}@media(max-width:700px){.cards{grid-template-columns:1fr}body{padding:14px}.wide{grid-column:auto}header{display:block}.pos{font-size:19px}}
</style>
<header><div><div class="tag">Core Basic / Liquid handler</div><h1>Teach the deck</h1><small>96 wells · A–H × 1–12 · 9 mm spacing</small></div><button id="export">Export calibration</button></header>
<div class="status" id="status">Connecting…</div><div id="error" role="alert"></div>
<div class="cards">
<section><h2>1 · Establish position</h2><p class="hint">Clear the homing paths, especially below the tip. Home X/Y and Z before teaching. Home All also homes the syringe A axis. Every teaching home first raises Z to travel height; when Z is unreferenced it rises by that distance (55 mm with this calibration), so leave that much room above it.</p>
<div class="row"><button class="action" data-act="home_all">Home all (X/Y/Z/A)</button><button class="action" data-act="home_xy">Home X / Y</button><button class="action" data-act="home_z">Home Z</button><button class="action" data-act="position">Read position</button></div>
<div class="pos" id="position">X — &nbsp; Y — &nbsp; Z —</div><p id="home" class="hint"></p>
<p class="hint">All motors release after each operation. Do not push the axes by hand: movement while released is not measured.</p><button class="action" data-act="invalidate">Axes moved by hand / re-home</button>
</section>
<section><h2>2 · Jog the tip</h2><p class="hint">Raise Z above obstacles before moving sideways. Start with small increments near the plate.</p>
<div class="row"><label>Step <select id="step"><option value="0.1">0.1 mm</option><option value="1" selected>1 mm</option><option value="10">10 mm</option></select></label></div>
<div class="row"><button class="jog" data-axis="X" data-dir="-1">X −</button><button class="jog" data-axis="X" data-dir="1">X +</button><button class="jog" data-axis="Y" data-dir="-1">Y −</button><button class="jog" data-axis="Y" data-dir="1">Y +</button></div>
<div class="row"><button class="jog" data-axis="Z" data-dir="-1">Z ↓</button><button class="jog" data-axis="Z" data-dir="1">Z ↑</button></div><p class="hint">Each click finishes and releases the motors before the next click is accepted.</p>
</section>
<section class="wide"><h2>3 · Locate the plate</h2><p class="hint">Align the tip over the center of A1, then A12, then H1. Keep the tip clear of the plate while locating X/Y. Capture H12 independently to check the calculated grid. These points define X/Y; dispense height is taught separately.</p>
<table><thead><tr><th>Point</th><th>Saved X / Y / Z (mm)</th><th></th></tr></thead><tbody id="platepoints"></tbody></table><div id="geometry" class="status">Capture A1, A12, and H1 to calculate the grid.</div><div class="grid" id="grid"></div>
</section>
<section><h2>4 · Reservoir & heights</h2><p class="hint">Reservoir: teach the tip at the aspiration location and immersion depth. Dispense Z: teach the desired height in a well. Travel Z: teach a height that clears every obstacle along the route.</p><table><tbody id="otherpoints"></tbody></table><p id="heights" class="hint"></p></section>
<section><h2>Calibration file</h2><label>Name <input id="name" maxlength="40" value="96-well plate"></label><label>Tip / setup notes <input id="notes" maxlength="160" placeholder="Tip length, reservoir, plate holder…"></label><button class="primary" id="metadata">Save name & notes</button><p class="hint">Captured points persist on this Core. Recheck alignment after moving labware or changing the tip. This screen teaches coordinates; it does not aspirate or dispense.</p><button id="clear">Clear saved calibration</button><p id="persist" class="hint"></p></section>
<section class="wide"><h2>5 · Dry run the plate</h2><p class="hint">Reservoir → A1–H1 → reservoir → A2–H2, through column 12. Uses the taught reservoir and dispense depths, staying at dispense Z between the eight wells and raising to travel Z for reservoir trips. Requests the configured maximum speeds (XY 500 mm/s, Z 5 mm/s); acceleration limits still apply. No syringe movement. All motors release when finished.</p><label><input type="checkbox" id="trial"> Allow H12 error up to 2 mm for this dry run only</label><button id="dryrun" class="primary">Run all 96 wells</button> <button id="stopdry">Stop after current location</button><p class="hint">Stop finishes the current location and raises to travel Z before releasing motors. It is not an emergency stop.</p></section>
<section class="wide"><h2>Connection log</h2><button class="action" data-act="endstops">Read limit switches</button><p class="hint">Reports switch states below without moving. The syringe switch is a_min.</p><pre id="log"></pre>
<h2>A homing diagnostic</h2><p class="hint">Moves only the syringe toward its home switch, then backs off and approaches again. Clear the full syringe travel and be ready to switch off power if it does not stop. The M5 switch display cannot update during homing.</p><button class="action" data-act="settings">Read motion settings</button> <button class="action" data-act="home_a_diag">Run A-only homing test</button> <a href="/api/a-homing-trace" target="_blank">View saved diagnostic log</a></section>
</div>
<script>
let state={},pending=false,loaded=false,refreshing=false;
const labels={a1:'A1 center',a12:'A12 center',h1:'H1 center',h12:'H12 check',reservoir:'Reservoir XYZ',dispense:'Dispense Z',travel:'Travel Z'};
for(const r of 'ABCDEFGH')for(let c=1;c<=12;c++){const w=r+c;let e=document.createElement('div');e.className='well'+(['A1','A12','H1'].includes(w)?' anchor':w==='H12'?' check':'');e.textContent=w;document.getElementById('grid').append(e)}
function pointRows(keys,id){document.getElementById(id).innerHTML=keys.map(k=>`<tr><td>${labels[k]}</td><td id="p-${k}">—</td><td><button class="capture" data-point="${k}">Capture</button></td></tr>`).join('')}
pointRows(['a1','a12','h1','h12'],'platepoints');pointRows(['reservoir','dispense','travel'],'otherpoints');
async function post(path,data){pending=true;render();try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');document.getElementById('error').textContent='';}catch(e){document.getElementById('error').textContent=e.message}finally{pending=false;await refresh()}}
function render(){const busy=pending||state.busy;document.getElementById('status').textContent=state.message||'Connecting…';document.getElementById('position').textContent=state.position?['X','Y','Z'].map(a=>a+' '+state.position[a.toLowerCase()].toFixed(2)).join('   '):'X —   Y —   Z —';document.getElementById('home').textContent=`Homed this session: X/Y ${state.xyHomed?'yes':'no'} · Z ${state.zHomed?'yes':'no'}`;
for(const b of document.querySelectorAll('.action,.jog,.capture')){let needsHome=b.classList.contains('jog')||b.classList.contains('capture');b.disabled=busy||!state.ready||(needsHome&&!(state.xyHomed&&state.zHomed))}
document.getElementById('dryrun').disabled=busy||!state.ready||!state.xyHomed||!state.zHomed||!state.heightsValid;document.getElementById('stopdry').disabled=!state.dryRunning||state.dryStopRequested;document.getElementById('trial').disabled=busy;
for(const [k,label] of Object.entries(labels)){const p=state.points?.[k];document.getElementById('p-'+k).textContent=p?[p.x,p.y,p.z].map(v=>v.toFixed(2)).join(' / '):'—'}
document.getElementById('geometry').textContent=state.geometry||'Capture A1, A12, and H1.';document.getElementById('heights').textContent=state.heights||'';document.getElementById('log').textContent=state.log||'';document.getElementById('persist').textContent=state.saved?'Saved on the Core.':'No calibration saved yet.';
for(const b of document.querySelectorAll('#metadata,#clear'))b.disabled=busy;
if(!loaded&&state.name!==undefined){document.getElementById('name').value=state.name;document.getElementById('notes').value=state.notes||'';loaded=true}
}
async function refresh(){if(refreshing)return;refreshing=true;try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error('Controller unavailable');state=await r.json();render()}catch(e){state.ready=false;render();document.getElementById('status').textContent='Controller unreachable — controls disabled'}finally{refreshing=false}}
document.querySelectorAll('.action').forEach(b=>b.onclick=()=>{if(b.dataset.act.startsWith('home')&&!confirm(b.dataset.act==='home_a_diag'?'Is the full syringe travel clear, and are you ready to observe A-only homing?':`Are the homing paths clear${b.dataset.act==='home_all'?' for X/Y/Z and syringe A':''}? ${state.zHomed?'Z will rise to at least travel height first.':'Z is unreferenced: allow '+(state.points?.travel?.z??'the travel height')+' mm of upward clearance before homing.'}`))return;post('/api/action',{action:b.dataset.act})});
document.querySelectorAll('.jog').forEach(b=>b.onclick=()=>post('/api/action',{action:'jog',axis:b.dataset.axis,delta:Number(b.dataset.dir)*Number(document.getElementById('step').value)}));
document.querySelectorAll('.capture').forEach(b=>b.onclick=()=>post('/api/action',{action:'capture',point:b.dataset.point}));
document.getElementById('dryrun').onclick=()=>post('/api/action',{action:'dry_run',allowTwoMm:document.getElementById('trial').checked});
document.getElementById('stopdry').onclick=()=>post('/api/action',{action:'stop_dry_run'});
document.getElementById('metadata').onclick=()=>post('/api/metadata',{name:document.getElementById('name').value,notes:document.getElementById('notes').value});document.getElementById('clear').onclick=()=>{if(confirm('Clear all taught points on this Core?'))post('/api/clear',{})};document.getElementById('export').onclick=()=>location.href='/api/calibration';refresh();setInterval(refresh,1200);
</script></html>)HTML";
